<?php 
/**
 * The PGRR portal is a resource for sharing genomic data in a resource community.
 * Copyright (C) 2015  University of Pittsburgh
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 */

/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse 7.2.232

*/

function formthrottle_check()
{
	if (!function_exists("sqlite_open")) 
	{
		return '1';
	}

	$retCode ='5';
	if ($db = @sqlite_open('muse-throttle-db', 0666, $sqliteerror)) 
	{
	    $res = @sqlite_query($db, "SELECT 1 FROM sqlite_master WHERE type='table' AND name='Submission_History';",  $sqliteerror);
	    if ($res == null or @sqlite_num_rows($res) == 0 or @sqlite_fetch_single($res) != 1) 
	    {
			$created = @sqlite_exec($db, "CREATE TABLE Submission_History (IP VARCHAR(39), Submission_Date TIMESTAMP)",  $sqliteerror);
			if($created)
			{
				@sqlite_exec($db, "INSERT INTO Submission_History (IP,Submission_Date) VALUES ('256.256.256.256', DATETIME('now'))",  $sqliteerror);
			}
			else
			{
				$retCode = '2';
			}
		}
		if($retCode == '5')
		{
			$res = @sqlite_query($db, "SELECT COUNT(1) FROM Submission_History;",  $sqliteerror);
			if ($res != null and @sqlite_num_rows($res) > 0 and @sqlite_fetch_single($res) > 0) 
				$retCode = '0';
			else
				$retCode = '3';
		}
	    @sqlite_close($db);

	} 
	else
		$retCode = '4';
		
	return $retCode;
}	

function formthrottle_too_many_submissions($ip)
{
	$tooManySubmissions = false;
	if (function_exists("sqlite_open") and $db = @sqlite_open('muse-throttle-db', 0666, $sqliteerror)) 
	{
		$ip = @sqlite_escape_string($ip);
		@sqlite_exec($db, "DELETE FROM Submission_History WHERE Submission_Date < DATETIME('now','-2 hours')",  $sqliteerror);
		@sqlite_exec($db, "INSERT INTO Submission_History (IP,Submission_Date) VALUES ('$ip', DATETIME('now'))",  $sqliteerror);
		$res = @sqlite_query($db, "SELECT COUNT(1) FROM Submission_History WHERE IP = '$ip';",  $sqliteerror);
		if (@sqlite_num_rows($res) > 0 and @sqlite_fetch_single($res) > 25) 
			$tooManySubmissions = true;
		@sqlite_close($db);

	}
	return $tooManySubmissions;
}
?>