<?php
/**
 * The PGRR portal is a resource for sharing genomic data in a resource community.
 * Copyright (C) 2015  University of Pittsburgh
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 */
/**
*  implement hook_menu()
*/

function dbmi_utils_menu(){
	$items['admin/config/dbmi'] = array(
      'title' => 'Department of Biomedical Informatics',
      'description' => 'Site settings',
      'position' => 'left',
      'weight' => 2,
      'page callback' => 'system_admin_menu_block_page',
      'access arguments' => array('access administration pages'),
      'file' => 'system.admin.inc',
      'file path' => drupal_get_path('module', 'system'),
	);
 
	$items['admin/config/dbmi/site'] = array(
        'title' => 'Site settings',
        'description' => 'Configure settings for the site.',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('dbmi_utils_settings_form'),
        'access arguments' => array('administer site configuration'),
        'file' => 'dbmi_utils.admin.inc',
	);
	return $items;
}

/**
*  implement hook_mail_alter()
*/

function dbmi_utils_mail_alter(&$message){	
	$variable = variable_get('dbmi_debug_mode');
	if($variable && user_is_logged_in()){
		global $user;
		//debug mode on, send email to current user and write the message to Recent log messages
		$debug_mode_message = "You're recieving this message because the system is in debug mode. The message should be \n sent to " . $message['to']. "\n ";
		$message['to'] = $user->mail;
		
		if(isset($message['headers']['Cc'])){
			$debug_mode_message .= "Cc to: " . $message['headers']['Cc'] . "\n ";
			$message['headers']['Cc'] = $user->mail;
		}
		if(isset($message['headers']['Bcc'])){
			$debug_mode_message .= "Bcc to: " . $message['headers']['Bcc'] . "\n ";
			$message['headers']['Bcc'] = $user->mail;
		}
		$debug_mode_message .= "\n Original Message: \n ";
		$message['body'][0] = $debug_mode_message . $message['body'][0];
		watchdog('email message', $message['body'][0], null, WATCHDOG_NOTICE, null);
	}
}

function dbmi_utils_user_cancel_methods_alter(&$methods){
	$var = variable_get('allow_delete_user_content', 0);
	if(!$var) 
	{
		unset($methods['user_cancel_delete']);
	}
	
}
